name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
      run: mkdir -p /path/to/artifact

    - name: Set java12
      uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: Set java12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        

    - name: Build Eureka with Maven
      run: |
        cd eureka
        mvn package 
        run: mv target/*.jar /path/to/artifact
        cd 
        
    - name: Build Config with Maven
      run: |
        cd config
        mvn package 
        run: mv target/*.jar /path/to/artifact
        cd
   
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: /path/to/artifact

    
